[
  {
    code: 'swsh4',
    ptcgoCode: 'VIV',
    name: 'Vivid Voltage',
    series: 'Sword & Shield',
    totalCards: 185,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '11/13/2020',
    symbolUrl: 'https://images.pokemontcg.io/swsh4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/swsh4/logo.png',
    updatedAt: '11/13/2020 16:20:00'
  },
  {
    code: 'swsh35',
    ptcgoCode: 'CPA',
    name: 'Champion\'s Path',
    series: 'Sword & Shield',
    totalCards: 73,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '09/25/2020',
    symbolUrl: 'https://images.pokemontcg.io/swsh35/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/swsh35/logo.png',
    updatedAt: '10/25/2020 13:45:00'
  },
  {
    code: 'swsh3',
    ptcgoCode: 'DAA',
    name: 'Darkness Ablaze',
    series: 'Sword & Shield',
    totalCards: 189,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '08/14/2020',
    symbolUrl: 'https://images.pokemontcg.io/swsh3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/swsh3/logo.png',
    updatedAt: '10/25/2020 13:45:00'
  },
  {
    code: 'swsh2',
    ptcgoCode: 'RCL',
    name: 'Rebel Clash',
    series: 'Sword & Shield',
    totalCards: 192,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '05/01/2020',
    symbolUrl: 'https://images.pokemontcg.io/swsh2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/swsh2/logo.png',
    updatedAt: '09/25/2020 10:09:00'
  },
  {
    code: 'swsh1',
    ptcgoCode: 'SSH',
    name: 'Sword & Shield',
    series: 'Sword & Shield',
    totalCards: 202,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '02/07/2020',
    symbolUrl: 'https://images.pokemontcg.io/swsh1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/swsh1/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'swshp',
    ptcgoCode: 'PR-SWSH',
    name: 'SWSH Black Star Promos',
    series: 'Sword & Shield',
    totalCards: 74,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '11/15/2019',
    symbolUrl: 'https://images.pokemontcg.io/swshp/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/swshp/logo.png',
    updatedAt: '11/15/2020 10:00:00'
  },
  {
    code: 'sm12',
    ptcgoCode: 'CEC',
    name: 'Cosmic Eclipse',
    series: 'Sun & Moon',
    totalCards: 236,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '11/01/2019',
    symbolUrl: 'https://images.pokemontcg.io/sm12/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm12/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'sm115',
    ptcgoCode: 'HIF',
    name: 'Hidden Fates',
    series: 'Sun & Moon',
    totalCards: 68,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '08/23/2019',
    symbolUrl: 'https://images.pokemontcg.io/sm115/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm115/logo.png',
    updatedAt: '08/23/2019 15:59:00'
  },
  {
    code: 'sma',
    name: 'Shiny Vault',
    series: 'Sun & Moon',
    totalCards: 94,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '08/23/2019',
    symbolUrl: 'https://images.pokemontcg.io/sma/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sma/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'sm11',
    ptcgoCode: 'UNM',
    name: 'Unified Minds',
    series: 'Sun & Moon',
    totalCards: 236,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '08/02/2019',
    symbolUrl: 'https://images.pokemontcg.io/sm11/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm11/logo.png',
    updatedAt: '09/25/2020 10:09:00'
  },
  {
    code: 'sm10',
    ptcgoCode: 'UNB',
    name: 'Unbroken Bonds',
    series: 'Sun & Moon',
    totalCards: 214,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '05/03/2019',
    symbolUrl: 'https://images.pokemontcg.io/sm10/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm10/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'det1',
    ptcgoCode: 'DET',
    name: 'Detective Pikachu',
    series: 'Sun & Moon',
    totalCards: 18,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '04/05/2019',
    symbolUrl: 'https://images.pokemontcg.io/det1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/det1/logo.png',
    updatedAt: '04/25/2019 22:26:00'
  },
  {
    code: 'sm9',
    ptcgoCode: 'TEU',
    name: 'Team Up',
    series: 'Sun & Moon',
    totalCards: 181,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '02/01/2019',
    symbolUrl: 'https://images.pokemontcg.io/sm9/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm9/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'sm8',
    ptcgoCode: 'LOT',
    name: 'Lost Thunder',
    series: 'Sun & Moon',
    totalCards: 214,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '11/02/2018',
    symbolUrl: 'https://images.pokemontcg.io/sm8/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm8/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'sm75',
    ptcgoCode: 'DRM',
    name: 'Dragon Majesty',
    series: 'Sun & Moon',
    totalCards: 70,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '09/07/2018',
    symbolUrl: 'https://images.pokemontcg.io/sm75/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm75/logo.png',
    updatedAt: '10/01/2018 21:54:00'
  },
  {
    code: 'sm7',
    ptcgoCode: 'CES',
    name: 'Celestial Storm',
    series: 'Sun & Moon',
    totalCards: 168,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '08/03/2018',
    symbolUrl: 'https://images.pokemontcg.io/sm7/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm7/logo.png',
    updatedAt: '02/19/2019 23:25:00'
  },
  {
    code: 'sm6',
    ptcgoCode: 'FLI',
    name: 'Forbidden Light',
    series: 'Sun & Moon',
    totalCards: 131,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '05/04/2018',
    symbolUrl: 'https://images.pokemontcg.io/sm6/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm6/logo.png',
    updatedAt: '02/19/2019 23:25:00'
  },
  {
    code: 'sm5',
    ptcgoCode: 'UPR',
    name: 'Ultra Prism',
    series: 'Sun & Moon',
    totalCards: 156,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '02/02/2018',
    symbolUrl: 'https://images.pokemontcg.io/sm5/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm5/logo.png',
    updatedAt: '02/19/2019 23:25:00'
  },
  {
    code: 'sm4',
    ptcgoCode: 'CIN',
    name: 'Crimson Invasion',
    series: 'Sun & Moon',
    totalCards: 111,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/03/2017',
    symbolUrl: 'https://images.pokemontcg.io/sm4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm4/logo.png',
    updatedAt: '02/19/2019 23:25:00'
  },
  {
    code: 'sm35',
    ptcgoCode: 'SLG',
    name: 'Shining Legends',
    series: 'Sun & Moon',
    totalCards: 73,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '10/06/2017',
    symbolUrl: 'https://images.pokemontcg.io/sm35/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm35/logo.png',
    updatedAt: '02/19/2019 23:25:00'
  },
  {
    code: 'sm3',
    ptcgoCode: 'BUS',
    name: 'Burning Shadows',
    series: 'Sun & Moon',
    totalCards: 147,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '08/05/2017',
    symbolUrl: 'https://images.pokemontcg.io/sm3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm3/logo.png',
    updatedAt: '02/19/2019 23:25:00'
  },
  {
    code: 'sm2',
    ptcgoCode: 'GRI',
    name: 'Guardians Rising',
    series: 'Sun & Moon',
    totalCards: 145,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '05/05/2017',
    symbolUrl: 'https://images.pokemontcg.io/sm2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm2/logo.png',
    updatedAt: '02/19/2019 23:25:00'
  },
  {
    code: 'sm1',
    ptcgoCode: 'SUM',
    name: 'Sun & Moon',
    series: 'Sun & Moon',
    totalCards: 149,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '02/03/2017',
    symbolUrl: 'https://images.pokemontcg.io/sm1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/sm1/logo.png',
    updatedAt: '04/10/2019 19:59:00'
  },
  {
    code: 'smp',
    ptcgoCode: 'PR-SM',
    name: 'SM Black Star Promos',
    series: 'Sun & Moon',
    totalCards: 156,
    standardLegal: true,
    expandedLegal: true,
    releaseDate: '02/03/2017',
    symbolUrl: 'https://images.pokemontcg.io/smp/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/smp/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'xy12',
    ptcgoCode: 'EVO',
    name: 'Evolutions',
    series: 'XY',
    totalCards: 108,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/02/2016',
    symbolUrl: 'https://images.pokemontcg.io/xy12/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy12/logo.png',
    updatedAt: '09/25/2020 10:09:00'
  },
  {
    code: 'xy11',
    ptcgoCode: 'STS',
    name: 'Steam Siege',
    series: 'XY',
    totalCards: 114,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '08/03/2016',
    symbolUrl: 'https://images.pokemontcg.io/xy11/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy11/logo.png',
    updatedAt: '04/10/2019 19:59:00'
  },
  {
    code: 'xy10',
    ptcgoCode: 'FCO',
    name: 'Fates Collide',
    series: 'XY',
    totalCards: 124,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '05/02/2016',
    symbolUrl: 'https://images.pokemontcg.io/xy10/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy10/logo.png',
    updatedAt: '09/03/2018 11:49:00'
  },
  {
    code: 'g1',
    ptcgoCode: 'GEN',
    name: 'Generations',
    series: 'XY',
    totalCards: 115,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '02/22/2016',
    symbolUrl: 'https://images.pokemontcg.io/g1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/g1/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'xy9',
    ptcgoCode: 'BKP',
    name: 'BREAKpoint',
    series: 'XY',
    totalCards: 122,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '02/03/2016',
    symbolUrl: 'https://images.pokemontcg.io/xy9/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy9/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'xy8',
    ptcgoCode: 'BKT',
    name: 'BREAKthrough',
    series: 'XY',
    totalCards: 162,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/04/2015',
    symbolUrl: 'https://images.pokemontcg.io/xy8/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy8/logo.png',
    updatedAt: '04/10/2019 19:59:00'
  },
  {
    code: 'xy7',
    ptcgoCode: 'AOR',
    name: 'Ancient Origins',
    series: 'XY',
    totalCards: 98,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '08/12/2015',
    symbolUrl: 'https://images.pokemontcg.io/xy7/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy7/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'xy6',
    ptcgoCode: 'ROS',
    name: 'Roaring Skies',
    series: 'XY',
    totalCards: 108,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '05/06/2015',
    symbolUrl: 'https://images.pokemontcg.io/xy6/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy6/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'dc1',
    ptcgoCode: 'DCR',
    name: 'Double Crisis',
    series: 'XY',
    totalCards: 34,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '03/25/2015',
    symbolUrl: 'https://images.pokemontcg.io/dc1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dc1/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'xy5',
    ptcgoCode: 'PRC',
    name: 'Primal Clash',
    series: 'XY',
    totalCards: 160,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '02/04/2015',
    symbolUrl: 'https://images.pokemontcg.io/xy5/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy5/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'xy4',
    ptcgoCode: 'PHF',
    name: 'Phantom Forces',
    series: 'XY',
    totalCards: 119,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/05/2014',
    symbolUrl: 'https://images.pokemontcg.io/xy4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy4/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'xy3',
    ptcgoCode: 'FFI',
    name: 'Furious Fists',
    series: 'XY',
    totalCards: 111,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '08/13/2014',
    symbolUrl: 'https://images.pokemontcg.io/xy3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy3/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'xy2',
    ptcgoCode: 'FLF',
    name: 'Flashfire',
    series: 'XY',
    totalCards: 106,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '05/07/2014',
    symbolUrl: 'https://images.pokemontcg.io/xy2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy2/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'xy1',
    ptcgoCode: 'XY',
    name: 'XY',
    series: 'XY',
    totalCards: 146,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '02/05/2014',
    symbolUrl: 'https://images.pokemontcg.io/xy1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy1/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'xy0',
    ptcgoCode: 'KSS',
    name: 'Kalos Starter Set',
    series: 'XY',
    totalCards: 39,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/08/2013',
    symbolUrl: 'https://images.pokemontcg.io/xy0/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xy0/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'bw11',
    ptcgoCode: 'LTR',
    name: 'Legendary Treasures',
    series: 'Black & White',
    totalCards: 113,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/06/2013',
    symbolUrl: 'https://images.pokemontcg.io/bw11/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw11/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'xyp',
    ptcgoCode: 'PR-XY',
    name: 'XY Black Star Promos',
    series: 'XY',
    totalCards: 183,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '10/12/2013',
    symbolUrl: 'https://images.pokemontcg.io/xyp/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/xyp/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'bw10',
    ptcgoCode: 'PLB',
    name: 'Plasma Blast',
    series: 'Black & White',
    totalCards: 101,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '08/14/2013',
    symbolUrl: 'https://images.pokemontcg.io/bw10/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw10/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'bw9',
    ptcgoCode: 'PLF',
    name: 'Plasma Freeze',
    series: 'Black & White',
    totalCards: 116,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '05/08/2013',
    symbolUrl: 'https://images.pokemontcg.io/bw9/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw9/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'bw8',
    ptcgoCode: 'PLS',
    name: 'Plasma Storm',
    series: 'Black & White',
    totalCards: 135,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '02/06/2013',
    symbolUrl: 'https://images.pokemontcg.io/bw8/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw8/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'bw7',
    ptcgoCode: 'BCR',
    name: 'Boundaries Crossed',
    series: 'Black & White',
    totalCards: 149,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/07/2012',
    symbolUrl: 'https://images.pokemontcg.io/bw7/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw7/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'dv1',
    ptcgoCode: 'DRV',
    name: 'Dragon Vault',
    series: 'Black & White',
    totalCards: 20,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '10/05/2012',
    symbolUrl: 'https://images.pokemontcg.io/dv1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dv1/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'bw6',
    ptcgoCode: 'DRX',
    name: 'Dragons Exalted',
    series: 'Black & White',
    totalCards: 124,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '08/15/2012',
    symbolUrl: 'https://images.pokemontcg.io/bw6/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw6/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'bw5',
    ptcgoCode: 'DEX',
    name: 'Dark Explorers',
    series: 'Black & White',
    totalCards: 108,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '05/09/2012',
    symbolUrl: 'https://images.pokemontcg.io/bw5/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw5/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'bw4',
    ptcgoCode: 'NXD',
    name: 'Next Destinies',
    series: 'Black & White',
    totalCards: 99,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '02/08/2012',
    symbolUrl: 'https://images.pokemontcg.io/bw4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw4/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'bw3',
    ptcgoCode: 'NVI',
    name: 'Noble Victories',
    series: 'Black & White',
    totalCards: 101,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '11/16/2011',
    symbolUrl: 'https://images.pokemontcg.io/bw3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw3/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'bw2',
    ptcgoCode: 'EPO',
    name: 'Emerging Powers',
    series: 'Black & White',
    totalCards: 98,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '08/31/2011',
    symbolUrl: 'https://images.pokemontcg.io/bw2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw2/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'bw1',
    ptcgoCode: 'BLW',
    name: 'Black & White',
    series: 'Black & White',
    totalCards: 114,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '04/25/2011',
    symbolUrl: 'https://images.pokemontcg.io/bw1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bw1/logo.png',
    updatedAt: '11/29/2018 19:56:00'
  },
  {
    code: 'bwp',
    ptcgoCode: 'PR-BLW',
    name: 'BW Black Star Promos',
    series: 'Black & White',
    totalCards: 101,
    standardLegal: false,
    expandedLegal: true,
    releaseDate: '03/01/2011',
    symbolUrl: 'https://images.pokemontcg.io/bwp/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/bwp/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'col1',
    ptcgoCode: 'CL',
    name: 'Call of Legends',
    series: 'HeartGold & SoulSilver',
    totalCards: 106,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/09/2011',
    symbolUrl: 'https://images.pokemontcg.io/col1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/col1/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'hgss4',
    ptcgoCode: 'TM',
    name: 'HS—Triumphant',
    series: 'HeartGold & SoulSilver',
    totalCards: 102,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '11/03/2010',
    symbolUrl: 'https://images.pokemontcg.io/hgss4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/hgss4/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'hgss3',
    ptcgoCode: 'UD',
    name: 'HS—Undaunted',
    series: 'HeartGold & SoulSilver',
    totalCards: 90,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/18/2010',
    symbolUrl: 'https://images.pokemontcg.io/hgss3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/hgss3/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'hgss2',
    ptcgoCode: 'UL',
    name: 'HS—Unleashed',
    series: 'HeartGold & SoulSilver',
    totalCards: 95,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/12/2010',
    symbolUrl: 'https://images.pokemontcg.io/hgss2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/hgss2/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'hsp',
    ptcgoCode: 'PR-HS',
    name: 'HGSS Black Star Promos',
    series: 'HeartGold & SoulSilver',
    totalCards: 25,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/10/2010',
    symbolUrl: 'https://images.pokemontcg.io/hsp/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/hsp/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'hgss1',
    ptcgoCode: 'HS',
    name: 'HeartGold & SoulSilver',
    series: 'HeartGold & SoulSilver',
    totalCards: 123,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/10/2010',
    symbolUrl: 'https://images.pokemontcg.io/hgss1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/hgss1/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'ru1',
    name: 'Pokémon Rumble',
    series: 'Other',
    totalCards: 16,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '12/02/2009',
    symbolUrl: 'https://images.pokemontcg.io/ru1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ru1/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'pl4',
    ptcgoCode: 'AR',
    name: 'Arceus',
    series: 'Platinum',
    totalCards: 99,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '11/04/2009',
    symbolUrl: 'https://images.pokemontcg.io/pl4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pl4/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'pl3',
    ptcgoCode: 'SV',
    name: 'Supreme Victors',
    series: 'Platinum',
    totalCards: 147,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/19/2009',
    symbolUrl: 'https://images.pokemontcg.io/pl3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pl3/logo.png',
    updatedAt: '03/07/2018 22:40:00'
  },
  {
    code: 'pl2',
    ptcgoCode: 'RR',
    name: 'Rising Rivals',
    series: 'Platinum',
    totalCards: 111,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/16/2009',
    symbolUrl: 'https://images.pokemontcg.io/pl2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pl2/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'pop9',
    name: 'POP Series 9',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '03/01/2009',
    symbolUrl: 'https://images.pokemontcg.io/pop9/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop9/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'pl1',
    ptcgoCode: 'PL',
    name: 'Platinum',
    series: 'Platinum',
    totalCards: 127,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/11/2009',
    symbolUrl: 'https://images.pokemontcg.io/pl1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pl1/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'dp7',
    ptcgoCode: 'SF',
    name: 'Stormfront',
    series: 'Diamond & Pearl',
    totalCards: 100,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '11/01/2008',
    symbolUrl: 'https://images.pokemontcg.io/dp7/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dp7/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'pop8',
    name: 'POP Series 8',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/01/2008',
    symbolUrl: 'https://images.pokemontcg.io/pop8/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop8/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'dp6',
    ptcgoCode: 'LA',
    name: 'Legends Awakened',
    series: 'Diamond & Pearl',
    totalCards: 146,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/01/2008',
    symbolUrl: 'https://images.pokemontcg.io/dp6/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dp6/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'dp5',
    ptcgoCode: 'MD',
    name: 'Majestic Dawn',
    series: 'Diamond & Pearl',
    totalCards: 100,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/01/2008',
    symbolUrl: 'https://images.pokemontcg.io/dp5/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dp5/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'pop7',
    name: 'POP Series 7',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '03/01/2008',
    symbolUrl: 'https://images.pokemontcg.io/pop7/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop7/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'dp4',
    ptcgoCode: 'GE',
    name: 'Great Encounters',
    series: 'Diamond & Pearl',
    totalCards: 106,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/01/2008',
    symbolUrl: 'https://images.pokemontcg.io/dp4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dp4/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'dp3',
    ptcgoCode: 'SW',
    name: 'Secret Wonders',
    series: 'Diamond & Pearl',
    totalCards: 132,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '11/01/2007',
    symbolUrl: 'https://images.pokemontcg.io/dp3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dp3/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'pop6',
    name: 'POP Series 6',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/01/2007',
    symbolUrl: 'https://images.pokemontcg.io/pop6/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop6/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'dp2',
    ptcgoCode: 'MT',
    name: 'Mysterious Treasures',
    series: 'Diamond & Pearl',
    totalCards: 123,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/01/2007',
    symbolUrl: 'https://images.pokemontcg.io/dp2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dp2/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'dp1',
    ptcgoCode: 'DP',
    name: 'Diamond & Pearl',
    series: 'Diamond & Pearl',
    totalCards: 130,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/01/2007',
    symbolUrl: 'https://images.pokemontcg.io/dp1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dp1/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'dpp',
    ptcgoCode: 'PR-DPP',
    name: 'DP Black Star Promos',
    series: 'Diamond & Pearl',
    totalCards: 56,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/01/2007',
    symbolUrl: 'https://images.pokemontcg.io/dpp/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/dpp/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'pop5',
    name: 'POP Series 5',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '03/01/2007',
    symbolUrl: 'https://images.pokemontcg.io/pop5/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop5/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'ex16',
    ptcgoCode: 'PK',
    name: 'Power Keepers',
    series: 'EX',
    totalCards: 108,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/02/2007',
    symbolUrl: 'https://images.pokemontcg.io/ex16/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex16/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'ex15',
    ptcgoCode: 'DF',
    name: 'Dragon Frontiers',
    series: 'EX',
    totalCards: 101,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '11/01/2006',
    symbolUrl: 'https://images.pokemontcg.io/ex15/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex15/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'ex14',
    ptcgoCode: 'CG',
    name: 'Crystal Guardians',
    series: 'EX',
    totalCards: 100,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/01/2006',
    symbolUrl: 'https://images.pokemontcg.io/ex14/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex14/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'pop4',
    name: 'POP Series 4',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/01/2006',
    symbolUrl: 'https://images.pokemontcg.io/pop4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop4/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'ex13',
    ptcgoCode: 'HP',
    name: 'Holon Phantoms',
    series: 'EX',
    totalCards: 110,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/01/2006',
    symbolUrl: 'https://images.pokemontcg.io/ex13/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex13/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'pop3',
    name: 'POP Series 3',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '04/01/2006',
    symbolUrl: 'https://images.pokemontcg.io/pop3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop3/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'ex12',
    ptcgoCode: 'LM',
    name: 'Legend Maker',
    series: 'EX',
    totalCards: 92,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/01/2006',
    symbolUrl: 'https://images.pokemontcg.io/ex12/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex12/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'ex11',
    ptcgoCode: 'DS',
    name: 'Delta Species',
    series: 'EX',
    totalCards: 113,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '10/31/2005',
    symbolUrl: 'https://images.pokemontcg.io/ex11/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex11/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'ex10',
    ptcgoCode: 'UF',
    name: 'Unseen Forces',
    series: 'EX',
    totalCards: 115,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/01/2005',
    symbolUrl: 'https://images.pokemontcg.io/ex10/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex10/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'pop2',
    name: 'POP Series 2',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/01/2005',
    symbolUrl: 'https://images.pokemontcg.io/pop2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop2/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'ex9',
    ptcgoCode: 'EM',
    name: 'Emerald',
    series: 'EX',
    totalCards: 106,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/01/2005',
    symbolUrl: 'https://images.pokemontcg.io/ex9/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex9/logo.png',
    updatedAt: '02/08/2020 09:00:00'
  },
  {
    code: 'ex8',
    ptcgoCode: 'DX',
    name: 'Deoxys',
    series: 'EX',
    totalCards: 107,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/01/2005',
    symbolUrl: 'https://images.pokemontcg.io/ex8/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex8/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'ex7',
    ptcgoCode: 'TRR',
    name: 'Team Rocket Returns',
    series: 'EX',
    totalCards: 109,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '11/01/2004',
    symbolUrl: 'https://images.pokemontcg.io/ex7/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex7/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'ex6',
    ptcgoCode: 'RG',
    name: 'FireRed & LeafGreen',
    series: 'EX',
    totalCards: 112,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/01/2004',
    symbolUrl: 'https://images.pokemontcg.io/ex6/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex6/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'pop1',
    name: 'POP Series 1',
    series: 'POP',
    totalCards: 17,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/01/2004',
    symbolUrl: 'https://images.pokemontcg.io/pop1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/pop1/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'ex5',
    ptcgoCode: 'HL',
    name: 'Hidden Legends',
    series: 'EX',
    totalCards: 101,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '06/01/2004',
    symbolUrl: 'https://images.pokemontcg.io/ex5/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex5/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'ex4',
    ptcgoCode: 'MA',
    name: 'Team Magma vs Team Aqua',
    series: 'EX',
    totalCards: 95,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '03/01/2004',
    symbolUrl: 'https://images.pokemontcg.io/ex4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex4/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'np',
    ptcgoCode: 'PR-NP',
    name: 'Nintendo Black Star Promos',
    series: 'NP',
    totalCards: 40,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '10/01/2003',
    symbolUrl: 'https://images.pokemontcg.io/np/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/np/logo.png',
    updatedAt: '05/01/2020 16:06:00'
  },
  {
    code: 'ex3',
    ptcgoCode: 'DR',
    name: 'Dragon',
    series: 'EX',
    totalCards: 97,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/18/2003',
    symbolUrl: 'https://images.pokemontcg.io/ex3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex3/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'ex2',
    ptcgoCode: 'SS',
    name: 'Sandstorm',
    series: 'EX',
    totalCards: 100,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/18/2003',
    symbolUrl: 'https://images.pokemontcg.io/ex2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex2/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'ex1',
    ptcgoCode: 'RS',
    name: 'Ruby & Sapphire',
    series: 'EX',
    totalCards: 109,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '07/01/2003',
    symbolUrl: 'https://images.pokemontcg.io/ex1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ex1/logo.png',
    updatedAt: '03/04/2018 10:35:00'
  },
  {
    code: 'ecard3',
    ptcgoCode: 'SK',
    name: 'Skyridge',
    series: 'E-Card',
    totalCards: 182,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/12/2003',
    symbolUrl: 'https://images.pokemontcg.io/ecard3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ecard3/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'ecard2',
    ptcgoCode: 'AQ',
    name: 'Aquapolis',
    series: 'E-Card',
    totalCards: 186,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '01/15/2003',
    symbolUrl: 'https://images.pokemontcg.io/ecard2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ecard2/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'ecard1',
    ptcgoCode: 'EX',
    name: 'Expedition Base Set',
    series: 'E-Card',
    totalCards: 165,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/15/2002',
    symbolUrl: 'https://images.pokemontcg.io/ecard1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/ecard1/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'base6',
    ptcgoCode: 'LC',
    name: 'Legendary Collection',
    series: 'Other',
    totalCards: 110,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '05/24/2002',
    symbolUrl: 'https://images.pokemontcg.io/base6/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/base6/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'neo4',
    ptcgoCode: 'N4',
    name: 'Neo Destiny',
    series: 'Neo',
    totalCards: 113,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '02/28/2002',
    symbolUrl: 'https://images.pokemontcg.io/neo4/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/neo4/logo.png',
    updatedAt: '09/25/2020 10:09:00'
  },
  {
    code: 'neo3',
    ptcgoCode: 'N3',
    name: 'Neo Revelation',
    series: 'Neo',
    totalCards: 66,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '09/21/2001',
    symbolUrl: 'https://images.pokemontcg.io/neo3/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/neo3/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'si1',
    name: 'Southern Islands',
    series: 'Other',
    totalCards: 18,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '07/31/2001',
    symbolUrl: 'https://images.pokemontcg.io/si1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/si1/logo.png',
    updatedAt: '01/28/2019 16:44:00'
  },
  {
    code: 'neo2',
    ptcgoCode: 'N2',
    name: 'Neo Discovery',
    series: 'Neo',
    totalCards: 75,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '06/01/2001',
    symbolUrl: 'https://images.pokemontcg.io/neo2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/neo2/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'neo1',
    ptcgoCode: 'N1',
    name: 'Neo Genesis',
    series: 'Neo',
    totalCards: 111,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '12/16/2000',
    symbolUrl: 'https://images.pokemontcg.io/neo1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/neo1/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'gym2',
    ptcgoCode: 'G2',
    name: 'Gym Challenge',
    series: 'Gym',
    totalCards: 132,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '10/16/2000',
    symbolUrl: 'https://images.pokemontcg.io/gym2/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/gym2/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'gym1',
    ptcgoCode: 'G1',
    name: 'Gym Heroes',
    series: 'Gym',
    totalCards: 132,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '08/14/2000',
    symbolUrl: 'https://images.pokemontcg.io/gym1/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/gym1/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
  {
    code: 'basep',
    ptcgoCode: 'PR',
    name: 'Wizards Black Star Promos',
    series: 'Base',
    totalCards: 53,
    standardLegal: false,
    expandedLegal: false,
    releaseDate: '07/01/1999',
    symbolUrl: 'https://images.pokemontcg.io/basep/symbol.png',
    logoUrl: 'https://images.pokemontcg.io/basep/logo.png',
    updatedAt: '08/14/2020 09:35:00'
  },
]